### ISSUE TITLE
Not able to import TrackletParser

### ISSUE THREAD

**Issue by AJAY31797** [holtvogt/tracklet_parser#4]
**Describe the bug**
Hi, 

I am trying to implement tracklet_parser on Google Colab. I cloned the repository and ran the setup.py file. For the next step as shown on in https://github.com/holtvogt/tracklet_parser, I am trying to import the TrackletParser. But it is not able to import it and shows error. 

**To Reproduce**

1. Go to Google Colab Notebook. 
2. Clone the repo using !git clone https://github.com/holtvogt/tracklet_parser
3. Set the current directory using %cd /content/tracklet_parser
4. Run the setup.py file using !python setup.py install
5. Import TrackletParser using from tracklet_parser import TrackletParser
6. See error. 

**Expected behavior**
The TrackletParser should be imported. However, I see error on importing.

**Screenshots**
The screenshot of the error is attached below.
![image](https://github.com/holtvogt/tracklet_parser/assets/53423573/0383ed29-b460-4300-bdfd-dfca05b8fc86)

Please let me know how to handle this.

**Comment by holtvogt** [comment]
There is an issue with the package structure. I will have a look and push a fix today. Thanks for letting me know!
